[package]
name = "fst-bin"
version = "0.1.2"
authors = ["Andrew Gallant <jamslam@gmail.com>"]
description = """
A command line tool for using finite state transducers to compactly represents
sets or maps of many strings (> 1 billion is possible). The command line tool
exposes functionality to search FSTs using regular expressions, Levenshtein
automata and range queries.
"""
documentation = "http://burntsushi.net/rustdoc/fst/"
homepage = "https://github.com/BurntSushi/fst"
repository = "https://github.com/BurntSushi/fst"
keywords = ["search", "information", "retrieval", "dictionary", "map"]
license = "Unlicense/MIT"

[[bin]]
name = "fst"

[dependencies]
bit-set = "0.2"
chan = "0.1"
csv = "0.14"
docopt = "0.6"
fst = { path = "..", version = "0.1" }
lines = "0.0"
num_cpus = "0.2"
rustc-serialize = "0.3"
tempdir = "0.3"

[profile.release]
debug = true
opt-level = 3
